/* ═══════════════════════════════════════════════════════════════════
   GENERATED FILE — DO NOT EDIT BY HAND.

   Domain data lifted verbatim from the desktop build (index.html) by
   scripts/extract-domain.js. Regenerate with:

       npm run mobile:domain

   Edit the data in index.html, never here: any change made here is lost on
   the next run, and the two builds would then disagree about what a species
   eats — which is the one thing they must never do.
   ═══════════════════════════════════════════════════════════════════ */
(function (global) {
  'use strict';

  const CAUSES=[
    {id:'vehicle',label:'Vehicle strike',icon:'🚗',color:'#ef4444'},
    {id:'dog',label:'Dog attack',icon:'🐕',color:'#f97316'},
    {id:'cat',label:'Cat attack',icon:'🐈',color:'#eab308'},
    {id:'orphaned',label:'Orphaned / joey',icon:'🍼',color:'#06b6d4'},
    {id:'habitat',label:'Habitat clearing',icon:'🌳',color:'#84cc16'},
    {id:'entangle',label:'Barbed wire / netting',icon:'⛓',color:'#ec4899'},
    {id:'disease',label:'Disease / mange',icon:'🦠',color:'#8b5cf6'},
    {id:'powerline',label:'Power line',icon:'⚡',color:'#fbbf24'},
    {id:'window',label:'Window strike',icon:'🪟',color:'#67e8f9'},
    {id:'pool',label:'Pool / drowning',icon:'💧',color:'#3b82f6'},
    {id:'fox',label:'Fox attack',icon:'🦊',color:'#ea580c'},
    {id:'human',label:'Human interaction',icon:'🧑',color:'#0ea5e9'},
    {id:'toxic',label:'Toxic / poison',icon:'☠️',color:'#dc2626'},
    {id:'other',label:'Other',icon:'➕',color:'#a78bfa'},
    {id:'unknown',label:'Unknown / found injured',icon:'❓',color:'#6b7280'},
  ];

  // ═══════════════════════════════════════════════════
  // SPECIES DATABASE
  // ═══════════════════════════════════════════════════
  const SPECIES=[
    {id:'brushtail',name:'Common Brushtail Possum',scientific:'Trichosurus vulpecula',color:'#c49a2a',
     food:[
       '🌿 Eucalyptus viminalis (manna gum) — primary browse, highest preference',
       '🌿 Eucalyptus radiata (narrow-leaved peppermint) — strong peppermint scent, highly palatable',
       '🌿 Eucalyptus ovata (swamp gum) — good secondary browse',
       '🌿 Eucalyptus obliqua (messmate stringybark) — accepted readily',
       '🌿 Eucalyptus globulus (blue gum) — high oil, offer alongside lower-oil species',
       '🌿 Acacia mearnsii (black wattle) — phyllodes and young growth',
       '🌿 Acacia melanoxylon (blackwood) — phyllodes, also sap sites on trunk',
       '🌸 Leptospermum laevigatum (coastal tea-tree) — flowers and young tips',
       '🌸 Callistemon species (bottlebrush) — nectar and flowers seasonally',
       '🍎 Exocarpos cupressiformis (native cherry) — small red fruit, highly favoured',
       '🍎 Billardiera scandens (apple berry) — native climbing berry',
       '🍎 Podocarpus lawrencei (plum pine) — fleshy red receptacle',
       '🍄 Mesophellia species (native truffle) — hypogeous fungi, important diet supplement',
       '🍄 Cortinarius species — native mushrooms, seasonal',
       '🌲 Eucalyptus viminalis manna — crystalline sugar exudate on bark and leaves, natural energy source',
       '🌲 Eucalyptus cambium — inner bark stripped in small amounts',
       '🌱 Leucopogon virgatus (beard-heath) — berries and young tips',
       '🌱 Coprosma quadrifida (prickly currant bush) — berries when fruiting',
     ],
     habitat:['Dry Sclerophyll Forest','Wet Sclerophyll Forest','Riparian Woodland','Urban parkland'],
     hollow:true,nocturnal:true,range:'1–5 ha',
     risks:{roads:'r',dogs:'r',cats:'r','barbed wire':'o','rat bait':'o'},
     cap:{km:3,max:4,mo:6},
     release:'Hollow-bearing trees essential (DBH >40cm). Min 3 ha connected canopy. Avoid 200m of arterial roads. Dusk release. Supplemental E. viminalis for 2 weeks.'},

    {id:'ringtail',name:'Common Ringtail Possum',scientific:'Pseudocheirus peregrinus',color:'#5c9e3a',
     food:[
       '🌿 Eucalyptus viminalis (manna gum) — important browse, second to tea-tree',
       '🌿 Eucalyptus radiata (narrow-leaved peppermint) — accepted well',
       '🌿 Leptospermum laevigatum (coastal tea-tree) — PRIMARY browse species',
       '🌿 Leptospermum continentale (prickly tea-tree) — young tips',
       '🌿 Pittosporum undulatum (sweet pittosporum) — young leaves and flowers',
       '🌿 Acacia species (wattle) — phyllodes, young growth',
       '🌸 Banksia marginata (silver banksia) — nectar and pollen',
       '🌸 Grevillea species — nectar seasonally',
       '🌸 Hakea species — nectar and flowers',
       '🌸 Rosa species (rose) — flowers and hips, highly favoured in gardens',
       '🍎 Exocarpos cupressiformis (native cherry) — small red fruit',
       '🍎 Billardiera scandens (apple berry) — climbing native berry',
       '🍎 Coprosma quadrifida (prickly currant bush) — red berries',
       '🍎 Solanum aviculare (kangaroo apple) — ripe orange fruit only',
       '🍄 Hypogeous fungi — truffles and underground fungi, seasonal supplement',
       '🌲 Eucalyptus viminalis manna — crystalline sugar exudate',
       '🌱 Myoporum species (boobialla) — leaves and fruit',
     ],
     habitat:['Heathland','Riparian Scrub','Dense urban gardens','Coastal scrub'],
     hollow:false,nocturnal:true,range:'0.5–1.5 ha',
     risks:{cats:'r',dogs:'r',roads:'o',pesticides:'o'},
     cap:{km:1.5,max:6,mo:6},
     release:'Dense shrub layer essential — builds dreys not hollows. Family group release preferred. Leptospermum and tea-tree at site critical.'},

    {id:'koala',name:'Koala',scientific:'Phascolarctos cinereus',color:'#7a9eb5',
     food:[
       '🌿 Eucalyptus viminalis (manna gum) — KEY primary species Victoria',
       '🌿 Eucalyptus camaldulensis (river red gum) — critical along waterways',
       '🌿 Eucalyptus globulus (blue gum) — accepted, high oil',
       '🌿 Eucalyptus radiata (narrow-leaved peppermint) — important secondary',
       '🌿 Eucalyptus obliqua (messmate stringybark) — important in ranges',
       '🌿 Eucalyptus rubida (candlebark) — accepted in higher elevations',
       '🌿 Eucalyptus ovata (swamp gum) — waterway corridors',
       '🌿 Eucalyptus polyanthemos (red box) — drier sites',
       '🌿 Eucalyptus leucoxylon (yellow gum) — SA border populations',
       '🌿 Corymbia maculata (spotted gum) — eastern populations',
       '🌲 Eucalyptus bark minerals — soil and bark occasionally eaten for mineral supplement',
       '🌱 Soil and clay — eaten for detoxification of phenolics (natural behaviour)',
     ],
     habitat:['Riparian Forest','Dry Sclerophyll Forest','Box Ironbark Forest'],
     hollow:false,nocturnal:false,range:'10–200 ha',
     risks:{roads:'r',dogs:'r',chlamydia:'r','heat stress':'o'},
     cap:{km:10,max:3,mo:12},
     release:'DELWP permit required. Food species MUST be confirmed at site before release. Vet chlamydia clearance mandatory. Never release lone male into established territory.'},

    {id:'sugar_glider',name:'Sugar Glider',scientific:'Petaurus breviceps',color:'#9b59b6',
     food:[
       '🌸 Banksia spinulosa (hairpin banksia) — nectar, primary energy source',
       '🌸 Banksia marginata (silver banksia) — nectar and pollen',
       '🌸 Grevillea species — nectar when flowering',
       '🌸 Callistemon sieberi (river bottlebrush) — nectar',
       '🌸 Hakea species — nectar seasonally',
       '🌸 Eucalyptus species — nectar and pollen from flowers',
       '🌲 Acacia melanoxylon (blackwood) — sap and gum from trunk wounds, KEY source',
       '🌲 Acacia mearnsii (black wattle) — gum exudate',
       '🌲 Eucalyptus viminalis manna — crystalline sugar exudate, high energy',
       '🌲 Lerp (psyllid secretions) — waxy covers on Eucalyptus leaves, important carbohydrate',
       '🌲 Honeydew — secretions from scale insects on Eucalyptus',
       '🪲 Lepidoptera larvae (caterpillars and moths) — protein source',
       '🪲 Coleoptera (beetles and larvae) — protein, especially autumn/winter',
       '🪲 Spiders and invertebrates — important protein supplement',
       '🪲 Orthoptera (grasshoppers, crickets) — seasonal protein',
     ],
     habitat:['Dry Sclerophyll Forest','Box Ironbark Forest','Riparian Woodland'],
     hollow:true,nocturnal:true,range:'1–2 ha (colony)',
     risks:{'barbed wire':'r',cats:'r',fragmentation:'r'},
     cap:{km:2,max:8,mo:6},
     release:'NEVER release alone — colony species. Group of 4–6 minimum. No barbed wire within 500m. Established Acacia gum trees essential at site.'},

    {id:'wombat',name:'Common Wombat',scientific:'Vombatus ursinus',color:'#795548',
     food:[
       '🌱 Rytidosperma species (wallaby grass) — primary grass species',
       '🌱 Poa labillardieri (tussock poa) — important tussock grass',
       '🌱 Poa sieberiana (grey tussock grass) — common in ranges',
       '🌱 Microlaena stipoides (weeping grass) — palatable fine grass',
       '🌱 Themeda triandra (kangaroo grass) — important seasonal grass',
       '🌱 Austrodanthonia species (wallaby grass) — widespread native grass',
       '🌱 Carex species (native sedges) — sedge layer, important in wet areas',
       '🌱 Juncus species (native rushes) — wetland margin foraging',
       '🍄 Mesophellia species (native truffle) — hypogeous fungi, KEY diet item',
       '🍄 Hysterangium species (native truffle) — important underground fungi',
       '🍄 Rhizopogon species (underground fungi) — root-associated fungi',
       '🍄 Cortinarius species — terrestrial mushrooms seasonally',
       '🌿 Native forbs and herbs — broad-leafed understorey species',
       '🌲 Bark and roots — occasionally gnawed for minerals',
       '🌱 Mosses — winter supplement in alpine areas',
     ],
     habitat:['Dry Sclerophyll Forest','Grassy Woodland','Alpine Ash Forest','Riparian Grassland'],
     hollow:false,nocturnal:true,range:'5–25 ha',
     risks:{roads:'r',mange:'r',dogs:'o','barbed wire':'o'},
     cap:{km:5,max:3,mo:12},
     release:'Mange clearance mandatory. Open grassy understorey with native grass species essential. Deep friable soil for burrow construction. Confirm fungi present via soil survey.'},

    {id:'kangaroo',name:'Eastern Grey Kangaroo',scientific:'Macropus giganteus',color:'#b5a240',
     food:[
       '🌱 Themeda triandra (kangaroo grass) — primary grass, highly preferred',
       '🌱 Microlaena stipoides (weeping grass) — fine-leafed, palatable',
       '🌱 Poa labillardieri (tussock poa) — important tussock species',
       '🌱 Rytidosperma species (wallaby grass) — widespread, important',
       '🌱 Austrodanthonia species — drier site grasslands',
       '🌱 Dichelachne species (plume grass) — forest understorey',
       '🌱 Lachnagrostis species (blown grass) — moist areas',
       '🌱 Native forbs and clovers — broad-leafed herbs in grassland',
       '🌿 Acacia species — browse in drought conditions',
       '🌿 Native shrub understorey — secondary browse when grasses dry off',
       '🍄 Native fungi — occasional supplement',
       '🌲 Bark — occasional mineral supplement',
     ],
     habitat:['Grassy Woodland','Dry Sclerophyll Forest edges','Open farmland with tree cover'],
     hollow:false,nocturnal:false,range:'100–1000 ha',
     risks:{roads:'r',dogs:'r',fences:'o','fright stress':'r'},
     cap:{km:10,max:5,mo:12},
     release:'Mob of 3–4 minimum. Large open grassy area with native grass species confirmed at site. Never near freeways. Scent acclimatisation — collect grass from release site 2 weeks before.'},

    {id:'echidna',name:'Short-beaked Echidna',scientific:'Tachyglossus aculeatus',color:'#607d8b',
     food:[
       '🪲 Iridomyrmex purpureus (meat ant) — PRIMARY food source',
       '🪲 Iridomyrmex bicknelli (small meat ant) — taken from surface trails',
       '🪲 Camponotus species (carpenter ants) — taken from decaying logs',
       '🪲 Polyrhachis species (spiny ants) — tree-dwelling species',
       '🪲 Nasutitermes species (termites) — from mound and wood galleries',
       '🪲 Coptotermes acinaciformis (termites) — from tree bases and logs',
       '🪲 Schedorhinotermes species (termites) — subterranean galleries',
       '🪲 Coleoptera larvae (beetle grubs) — extracted from decaying logs',
       '🪲 Earthworms — occasionally from moist soil',
       '🍄 Fungal spores — consumed incidentally when disturbing soil and logs',
     ],
     habitat:['Dry Sclerophyll Forest','Grassy Woodland','Rocky outcrops','Coastal heathland'],
     hollow:false,nocturnal:false,range:'50–200 ha',
     risks:{roads:'r',dogs:'o','garden netting':'o'},
     cap:{km:5,max:5,mo:12},
     release:'Highly adaptable. Confirm presence of ant and termite colonies at site. Check for garden netting and agricultural nets within 500m. Deep leaf litter and rotting logs essential.'},

    {id:'bandicoot',name:'Long-nosed Bandicoot',scientific:'Perameles nasuta',color:'#8d6e63',
     food:[
       '🪲 Earthworms (Oligochaeta) — primary food, critically important',
       '🪲 Coleoptera larvae (beetle grubs) — extracted from soil and mulch',
       '🪲 Scarab larvae (curl grubs) — dug from lawn and soil',
       '🪲 Isoptera (termites) — from moist soil galleries',
       '🪲 Spiders and invertebrates — broad invertebrate hunting',
       '🪲 Centipedes and millipedes — from leaf litter',
       '🍄 Mesophellia species (native truffle) — KEY hypogeous fungi',
       '🍄 Hysterangium species — underground fungi, sniffed out and dug',
       '🍄 Cortinarius species — terrestrial fungi seasonally',
       '🍄 Rhizopogon species — root-associated underground fungi',
       '🌱 Native tubers and bulbs — Dichopogon, Burchardia species',
       '🍎 Native berries — opportunistic when available',
     ],
     habitat:['Moist Sclerophyll Forest','Dense urban gardens with mulch and leaf litter'],
     hollow:false,nocturnal:true,range:'0.5–3 ha',
     risks:{cats:'r',foxes:'r',dogs:'r'},
     cap:{km:1.5,max:5,mo:6},
     release:'Cats are primary mortality cause — release only into cat-managed areas. Deep leaf litter, mulch and earthworm-rich soil essential. Confirm truffle-forming native vegetation at site.'},

    {id:'feathertail',name:'Feathertail Glider',scientific:'Acrobates pygmaeus',color:'#c0392b',
     food:[
       '🌸 Banksia spinulosa (hairpin banksia) — nectar, primary energy',
       '🌸 Banksia marginata (silver banksia) — nectar and pollen',
       '🌸 Grevillea species — nectar when flowering',
       '🌸 Callistemon species (bottlebrush) — nectar',
       '🌸 Hakea species — nectar seasonally',
       '🌸 Eucalyptus species — flowers, nectar and pollen',
       '🌸 Leptospermum species — nectar from flowers',
       '🌲 Lerp (psyllid secretions) — waxy covers on Eucalyptus, KEY carbohydrate',
       '🌲 Honeydew — scale insect secretions on Eucalyptus and Acacia',
       '🌲 Eucalyptus viminalis manna — crystalline exudate, high energy',
       '🌲 Acacia gum exudate — natural gum from trunk wounds',
       '🪲 Small moths and insects — protein supplement, caught in flight',
       '🪲 Psyllids and aphids — gleaned from leaf surfaces',
     ],
     habitat:['Wet Sclerophyll Forest','Dry Sclerophyll Forest','Coastal Banksia woodland'],
     hollow:true,nocturnal:true,range:'0.1–0.5 ha',
     risks:{cats:'r','barbed wire':'r',fragmentation:'r'},
     cap:{km:1,max:10,mo:6},
     release:'Group of 6 or more essential — highly social. Flowering Banksia and Grevillea at release site critical. Dense canopy connectivity required — cannot cross open ground.'},

    {id:'swamp_wallaby',name:'Swamp Wallaby',scientific:'Wallabia bicolor',color:'#2e7d32',
     food:[
       '🌿 Pteridium esculentum (bracken fern) — PRIMARY browse species, highly diagnostic',
       '🌿 Acacia melanoxylon (blackwood) — phyllodes and young growth',
       '🌿 Acacia mearnsii (black wattle) — phyllodes',
       '🌿 Acacia verticillata (prickly moses) — young tips',
       '🌿 Leptospermum species (tea-tree) — young tips and leaves',
       '🌿 Gahnia species (saw-sedge) — coarse sedge browse',
       '🌿 Lomandra longifolia (spiny-headed mat-rush) — young growth',
       '🌿 Poa species (tussock grass) — secondary grass browse',
       '🌸 Native flower heads — various understorey species seasonally',
       '🍎 Billardiera scandens (apple berry) — native climbing berry',
       '🍎 Exocarpos cupressiformis (native cherry) — small fruit',
       '🍄 Native fungi — occasionally, especially after rain',
       '🌱 Native grasses — secondary to browse, less important than in other macropods',
     ],
     habitat:['Wet Sclerophyll Forest understorey','Heathy Woodland','Riparian Scrub','Coastal Banksia scrub'],
     hollow:false,nocturnal:true,range:'10–30 ha',
     risks:{roads:'r',dogs:'r',cats:'o'},
     cap:{km:3,max:4,mo:6},
     release:'Dense understorey of bracken and tea-tree essential. More solitary than kangaroos — pairs acceptable for release. Evening release into wind. Bracken fern at site is a key indicator of suitability.'},

    // ── MONOTREMES ──────────────────────────────────────────────────────────────
    {id:'platypus',name:'Platypus',scientific:'Ornithorhynchus anatinus',color:'#0369a1',
     group:'Monotremes',
     food:[
       '🪲 Ephemeroptera (mayfly larvae) — primary prey, abundant in clean creek beds',
       '🪲 Plecoptera (stonefly larvae) — high-quality protein from fast-flowing riffles',
       '🪲 Trichoptera (caddisfly larvae) — taken from submerged logs and stones',
       '🪲 Diptera larvae (midge larvae, chironomids) — fine silt substrates',
       '🪲 Amphipoda (freshwater shrimp, Gammarus, Austrochiltonia) — in aquatic vegetation',
       '🪲 Crayfish / yabby juveniles (Cherax destructor) — bottom foraging',
       '🪲 Annelida (earthworms and aquatic worms) — bank burrow entrances at water edge',
       '🪲 Odonata larvae (dragonfly nymphs) — ambushed in vegetation',
       '🪲 Coleoptera larvae (water beetle larvae) — under stones',
       '🪲 Aquatic snails (Physa, Lymnaea) — scraped from rocks',
       '🪲 Isopoda (freshwater slaters) — leaf litter and submerged wood',
       '🪲 Copepoda and Ostracoda (microcrustaceans) — fine filtering in silt',
     ],
     habitat:['Freshwater streams','Riparian Forest','Lakes with clean cold water'],
     hollow:false,nocturnal:true,range:'10km+ of waterway',
     aquatic:true,
     risks:{'fishing line':'r','water pollution':'r','traps':'r','drought':'r'},
     cap:{km:3,max:2,mo:24},
     notes:'⚠️ SPECIALIST CARE: Platypus is a specialist that cannot survive in captivity without expert management. Food must be live aquatic invertebrates — no substitutes accepted. Contact DELWP / specialist wildlife vet immediately. Males have venomous spurs on hind limbs. Do not handle with bare hands. Source: Hawke & Munks (2012); Wildlife Victoria platypus care protocol.',
     release:'Release ONLY at point of rescue or upstream equivalent. Water quality must be verified. Do NOT release into any waterway with pollution, low flow, or introduced trout. Notify DELWP of any platypus rescue. Consult DPIE / Wildlife Health Australia before transport.'},

    // ── CARNIVOROUS MARSUPIALS (DASYURIDS) ──────────────────────────────────────
    {id:'tiger_quoll',name:'Spotted-tailed Quoll',scientific:'Dasyurus maculatus',color:'#7c2d12',
     group:'Dasyurids',
     food:[
       '🪲 Insects and large invertebrates — beetles, orthoptera, cockroaches (Periplaneta, Blabberus)',
       '🪲 Crayfish and freshwater yabbies — opportunistic near water',
       '🍎 Fruit and berries — occasional, Rubus, Exocarpos — NOT a primary dietary component',
       '🪲 Small mammals — mice, rats, small possums in wild; in care use pre-killed rodents only',
       '🪲 Birds and bird eggs — in wild only; in care use pre-killed chicks (day-old)',
       '🪲 Reptiles and lizards — skinks, geckos in wild; do not offer in care unless specialist',
       '🪲 Carrion and offal — supplement in care; kangaroo mince (lean, human-grade)',
       '🪲 Earthworms (Lumbricus terrestris) — accept readily as care supplement',
       '🪲 Mealworms (Tenebrio molitor) — calcium-dusted; high palatability in juveniles',
       '🪲 Crickets (Acheta domesticus) — gut-loaded, calcium-dusted; critical for young',
       '🪲 Large cockroaches (Shelfordella tartara) — excellent prey for juveniles',
       '🪲 Frogs (in wild) — Heleioporus, Limnodynastes; do not offer in care',
     ],
     habitat:['Wet Sclerophyll Forest','Riparian Forest','Montane Ash Forest'],
     hollow:true,nocturnal:true,range:'1000–4500 ha',
     risks:{roads:'r',dogs:'r','1080 baiting':'r','habitat loss':'r'},
     cap:{km:10,max:2,mo:24},
     endangered:'Vulnerable (EPBC Act)',
     notes:'⚠️ SPECIALIST CARE ONLY. Spotted-tailed Quoll is a Vulnerable species. Notify DEECA Wildlife Licensing immediately. Quolls are solitary and highly stressed by captivity. Minimise handling. They have sharp teeth and will bite. Use thick leather gloves. Source: Belcher (2004) quoll husbandry; DPIE care guidelines.',
     release:'Requires DELWP approval. Release only in large connected forest areas. Must be confirmed breeding population in area. Night release at known territory location. Notify DEECA and local ranger.'},

    {id:'antechinus',name:'Yellow-footed Antechinus',scientific:'Antechinus flavipes',color:'#713f12',
     group:'Dasyurids',
     food:[
       '🪲 Coleoptera (beetles and larvae) — primary prey, taken from bark and leaf litter',
       '🪲 Orthoptera (crickets and grasshoppers) — critical protein source',
       '🪲 Lepidoptera larvae (caterpillars and moths) — soft-bodied, high protein',
       '🪲 Araneae (spiders) — taken from web retreats and under bark',
       '🪲 Blattodea (cockroaches, Shelfordella tartara) — high palatability in captivity',
       '🪲 Mealworms (Tenebrio molitor) — calcium-dusted; staple captive diet',
       '🪲 Waxworms (Galleria mellonella) — high fat; supplement, not staple',
       '🪲 Crickets (Acheta domesticus, Gryllodes sigillatus) — gut-loaded essential',
       '🪲 Earthworms — taken in moist soil; offer fresh-killed in care',
       '🪲 Diptera (flies and larvae) — taken from decaying wood and fungi',
       '🍎 Nectar and fruit juice — occasional; Banksia nectar as supplement in care',
       '🌸 Invertebrates in flowers — gleans small insects and pollen from native flowers',
     ],
     habitat:['Dry Sclerophyll Forest','Box Ironbark Woodland','Mallee','Rocky outcrops'],
     hollow:false,nocturnal:true,range:'0.5–3 ha',
     risks:{cats:'r',foxes:'r','habitat fragmentation':'r'},
     cap:{km:1,max:5,mo:6},
     notes:'Important: Male antechinuses die en masse after mating season (late winter). A male found in poor condition after August is almost certainly in post-semelparous decline and has a poor prognosis. Focus care resources on females and juveniles. Source: Krajewski et al. (2009); ERS Dasyurid care sheet.',
     release:'Release near original capture location — strong site fidelity. Dense bark and hollow logs essential. Night release with food cache at entrance.'},

    {id:'dunnart',name:'Common Dunnart',scientific:'Sminthopsis murina',color:'#92400e',
     group:'Dasyurids',
     food:[
       '🪲 Acari (mites and small arachnids) — taken from leaf litter and soil',
       '🪲 Isopoda (slaters, Armadillidium) — common in gardens, readily taken',
       '🪲 Insect larvae (various) — Coleoptera, Lepidoptera larvae from soil',
       '🪲 Collembola (springtails) — tiny but important in leaf litter',
       '🪲 Small crickets (Gryllodes sigillatus) — reduced size juveniles for dunnarts',
       '🪲 Mealworms (Tenebrio molitor) — calcium-dusted; main captive protein',
       '🪲 Fruit flies (Drosophila) — excellent for very small individuals',
       '🪲 Small cockroaches (Pycnoscelus surinamensis) — juveniles of small species',
       '🪲 Earthworm segments — offered fresh-cut in tiny amounts',
       '🪲 Small spiders (Linyphiidae, Salticus) — caught from vegetation',
       '🪲 Blowfly pupae (Calliphora) — high fat, supplement only',
     ],
     habitat:['Mallee','Heathland','Dry Sclerophyll Woodland','Urban grassy areas with mulch'],
     hollow:false,nocturnal:true,range:'0.5–2 ha',
     risks:{cats:'r',foxes:'r','garden cats':'r'},
     cap:{km:0.5,max:5,mo:3},
     notes:'Dunnarts enter torpor in cold conditions — this is NORMAL. Do not warm a torpid dunnart rapidly; allow gradual warming in a quiet container at room temperature. Torpor is energy conservation, not illness. Tail fat stores (fat-tailed dunnart sub-species) indicate condition. Source: Turbill (2008) dunnart torpor research.',
     release:'Release at point of rescue. Dense mulch and leaf litter essential at site. Check for cat activity within 100m.'},

    // ── POSSUMS & GLIDERS (ADDITIONAL) ─────────────────────────────────────────
    {id:'mountain_brushtail',name:'Mountain Brushtail Possum',scientific:'Trichosurus cunninghami',color:'#a16207',
     group:'Possums & Gliders',
     food:[
       '🌿 Eucalyptus obliqua (messmate stringybark) — primary browse in mountain ash forests',
       '🌿 Eucalyptus regnans (mountain ash) — young leaves when available',
       '🌿 Eucalyptus delegatensis (alpine ash) — important in sub-alpine zones',
       '🌿 Acacia melanoxylon (blackwood) — phyllodes and young growth year-round',
       '🌿 Acacia dealbata (silver wattle) — phyllodes and young stems',
       '🌿 Pomaderris aspera (hazel pomaderris) — young leaves, highly palatable',
       '🌿 Prostanthera lasianthos (Victorian Christmas bush) — aromatic leaves',
       '🌿 Zieria arborescens (stinkwood) — leaves and young tips',
       '🌸 Banksia marginata (silver banksia) — flowers and nectar',
       '🍎 Rubus parvifolius (native raspberry) — ripe fruit seasonally',
       '🍎 Coprosma quadrifida (prickly currant bush) — red berries when fruiting',
       '🍄 Hypogeous fungi — truffles and underground fungi important in old growth',
       '🌲 Eucalyptus cambium — bark stripped for minerals and moisture',
       '🌱 Athyrium species (lady fern) — fronds occasionally; ferns as supplemental',
     ],
     habitat:['Wet Sclerophyll Forest','Mountain Ash Forest','Cool Temperate Rainforest'],
     hollow:true,nocturnal:true,range:'2–10 ha',
     risks:{roads:'r',dogs:'r','logging':'r'},
     cap:{km:3,max:3,mo:6},
     notes:'Mountain Brushtail Possums are significantly larger and more aggressive than Common Brushtails. Use thick gloves. They require wetter, cooler habitat for release — do not release in urban or warm lowland areas. Browse preferences differ from Common Brushtail: pomaderris and mountain ash browse is preferred over the manna gum/tea tree mix. Source: Tyndale-Biscoe & Renfree (1987); general husbandry guidelines.',
     release:'Cool-temperate wet sclerophyll forest essential. Minimum 20 ha of connected old-growth forest. Hollow trees with DBH >60cm required. Canopy continuity critical — cannot cross large clearings.'},

    {id:'greater_glider',name:'Greater Glider',scientific:'Petauroides volans',color:'#1e3a5f',
     group:'Possums & Gliders',
     food:[
       '🌿 Eucalyptus obliqua (messmate) — PRIMARY food; leaves only, highly specialised',
       '🌿 Eucalyptus regnans (mountain ash) — leaves; most important in tall forest',
       '🌿 Eucalyptus delegatensis (alpine ash) — subalpine to montane range',
       '🌿 Eucalyptus cypellocarpa (mountain grey gum) — important secondary browse',
       '🌿 Eucalyptus radiata (narrow-leaved peppermint) — accepted in some regions',
       '🌿 Eucalyptus globulus (blue gum) — accepted in coastal/lowland populations',
       '🌿 Eucalyptus baxteri (brown stringybark) — southern range populations',
       '🌿 Eucalyptus ovata (swamp gum) — waterway fringing populations',
       '🌿 Eucalyptus tricarpa (red ironbark) — drier zone populations only',
       '🌸 Eucalyptus pollen and flowers — very occasional seasonal supplement',
       '🌲 Eucalyptus bark (thin strips) — occasionally for moisture and minerals',
     ],
     habitat:['Mountain Ash Forest','Wet Sclerophyll Forest','Cool-moist Eucalypt Forest'],
     hollow:true,nocturnal:true,range:'5–50 ha',
     risks:{'habitat loss':'r',roads:'r','powerlines':'r'},
     cap:{km:5,max:3,mo:12},
     endangered:'Vulnerable (EPBC Act)',
     notes:'⚠️ CRITICAL DIETARY SPECIALIST. Greater Gliders eat ONLY eucalyptus leaves from specific species — they will often refuse to eat before accepting unfamiliar species. Do NOT offer any non-eucalyptus browse. Greater Gliders have very low energy requirements and should NOT be overfed. Obesity is a significant welfare risk in captivity. They are sensitive to warm temperatures (>26°C causes heat stress). Source: Kavanagh (2004); EPBC Recovery Plan; Smith (2010).',
     release:'Requires DELWP approval. Old-growth forest with hollow-bearing trees DBH >60cm mandatory. Cannot survive without intact dense forest canopy. Report to DEECA Conservation Regulator. Notify of any injured Greater Glider — they are a threatened species.'},

    {id:'leadbeaters_possum',name:'Leadbeater\'s Possum',scientific:'Gymnobelideus leadbeateri',color:'#7f1d1d',
     group:'Possums & Gliders',
     food:[
       '🌲 Acacia gum and exudate — PRIMARY food; wattle gum from trunk wounds is critical',
       '🌲 Eucalyptus sap — taken from insect-excavated sap runs on mountain ash',
       '🌲 Lerp (psyllid secretions) — important carbohydrate on Eucalyptus leaves',
       '🌲 Honeydew (Spondyliaspis, Ctenarytaina) — scale insect secretions on Eucalyptus',
       '🌲 Manna (E. viminalis exudate) — crystalline sugar from bark surface',
       '🪲 Beetles and beetle larvae (Coleoptera) — under bark of mountain ash; critical protein',
       '🪲 Moths and caterpillars (Lepidoptera) — important protein especially in breeding season',
       '🪲 Crickets (Acheta domesticus) — gut-loaded, calcium-dusted; main captive protein',
       '🪲 Mealworms (Tenebrio molitor) — calcium-dusted, offered sparingly',
       '🪲 Spiders (Salticidae, Theridiidae) — gleaned from bark and leaf surfaces',
       '🪲 Cockroaches — small species, high protein',
       '🌸 Nectar from Banksia and Grevillea — occasional supplement',
     ],
     habitat:['Mountain Ash Forest (>60 year old growth)','Montane Wet Sclerophyll'],
     hollow:true,nocturnal:true,range:'1–3 ha (colony)',
     risks:{'logging':'r','fire':'r','habitat loss':'r'},
     cap:{km:3,max:5,mo:12},
     endangered:'Critically Endangered (EPBC Act)',
     notes:'🔴 CRITICALLY ENDANGERED — NOTIFY DEECA IMMEDIATELY on rescue. Leadbeater\'s Possum is one of Australia\'s rarest mammals, restricted to the mountain ash forests of the Central Highlands. Any rescue must be reported to DEECA Conservation Regulator and DSE Threatened Species unit. These animals require colony management — single individuals often fail to thrive in isolation. DO NOT release without DSE coordination. Source: Macfarlane et al. (1997); Environment Australia (2003) Recovery Plan.',
     release:'DEECA approval mandatory. Release only into known Leadbeater\'s colony area. Tag and microchip required. Post-release monitoring required. Consult DSE Threatened Species Coordinator before any release attempt.'},

    // ── KANGAROOS & WALLABIES (ADDITIONAL) ─────────────────────────────────────
    {id:'western_grey_kangaroo',name:'Western Grey Kangaroo',scientific:'Macropus fuliginosus',color:'#78350f',
     group:'Kangaroos & Wallabies',
     food:[
       '🌱 Themeda triandra (kangaroo grass) — primary grass; very important in dry conditions',
       '🌱 Austrodanthonia species (wallaby grass) — widespread native grasses',
       '🌱 Dicanthium sericeum (Queensland blue grass) — northern populations',
       '🌱 Microlaena stipoides (weeping grass) — palatable, semi-shade tolerant',
       '🌱 Poa labillardieri (tussock poa) — tussock grassland species',
       '🌱 Chloris truncata (windmill grass) — dry open grassland',
       '🌱 Paspalidium jubiflorum (native millet) — summer growth',
       '🌱 Native forbs — Oxalis, Hovea, Glycine, Desmodium spp. broad-leafed herbs',
       '🌱 Lomandra longifolia (mat rush) — mature adults; young growth only',
       '🌿 Acacia shrubs — browse when grasses dry off; A. pycnantha, A. acinacea',
       '🌿 Saltbush (Atriplex) — dry zone populations; not Victorian primary',
       '🍄 Native fungi — occasional after rain; soil scratch-foraging',
     ],
     habitat:['Mallee','Dry Sclerophyll Woodland','Grassy Woodland','Open scrubland'],
     hollow:false,nocturnal:false,range:'100–2000 ha',
     risks:{roads:'r',dogs:'r',fences:'o','fright stress':'r'},
     cap:{km:10,max:5,mo:12},
     notes:'Western Grey Kangaroos are found in south-western Victoria and the Wimmera/Mallee. They are adapted to drier conditions than the Eastern Grey. DO NOT release Eastern Greys in Western Grey territory and vice versa — they have different habitat requirements. Stress-induced myopathy (capture myopathy) is a serious risk. Minimise pursuit, restraint time, and handling. Source: Dawson (1995); general macropod husbandry.',
     release:'Dry open woodland or mallee with native grass understory. Mob of 3–4 essential. Large (>1000 ha) continuous habitat preferred. No release near wineries or crop areas without prior permission.'},

    {id:'red_necked_wallaby',name:'Red-necked Wallaby',scientific:'Notamacropus rufogriseus',color:'#9a3412',
     group:'Kangaroos & Wallabies',
     food:[
       '🌱 Themeda triandra (kangaroo grass) — primary grass in clearings and forest edges',
       '🌱 Poa labillardieri (tussock poa) — wet sclerophyll understorey',
       '🌱 Microlaena stipoides (weeping grass) — fine-leafed preferred grass',
       '🌱 Rytidosperma species (wallaby grass) — important in open grassy woodland',
       '🌱 Lolium perenne (ryegrass) — accepts in captivity; not wild-type preference',
       '🌿 Acacia melanoxylon (blackwood) — young browse in forest habitat',
       '🌿 Acacia dealbata (silver wattle) — phyllodes and new growth',
       '🌿 Pomaderris aspera (hazel pomaderris) — occasionally browsed in wet forest',
       '🌿 Leptospermum species (tea-trees) — young tips in heathy woodland',
       '🌸 Native flower heads (Acacia, Olearia) — seasonal supplement',
       '🍎 Rubus parvifolius (native raspberry) — ripe fruit when available',
       '🍄 Native fungi — occasional, especially in wet forest post-rain',
     ],
     habitat:['Wet Sclerophyll Forest edges','Riparian Woodland','Heathy Woodland','Forest clearings'],
     hollow:false,nocturnal:true,range:'20–100 ha',
     risks:{roads:'r',dogs:'r',cats:'o'},
     cap:{km:5,max:5,mo:12},
     notes:'Red-necked Wallabies are common in the eastern highlands and coastal areas of Victoria. Joey Red-necked Wallabies are often confused with kangaroo joeys — check the characteristic red-rufous neck colouration in sub-adults. They are more solitary than Eastern Greys. Release requires a mob of at least 2–3. Source: Coulson (1990); Wildlife Victoria care sheet.',
     release:'Forest edge or wet sclerophyll with grassy clearing nearby. Native grass sward essential. 2–3 individuals minimum for release. Avoid areas with domestic dog access.'},

    // ── BANDICOOTS (ADDITIONAL) ─────────────────────────────────────────────────
    {id:'southern_brown_bandicoot',name:'Southern Brown Bandicoot',scientific:'Isoodon obesulus',color:'#44403c',
     group:'Bandicoots',
     food:[
       '🪲 Earthworms (Lumbricus terrestris) — primary food; live worms or fresh-killed',
       '🪲 Coleoptera larvae (curl grubs, scarab grubs) — dug from lawn and soil',
       '🪲 Isoptera (termites) — subterranean galleries; dig with long claws',
       '🪲 Coleoptera adults (ground beetles, Carabidae) — taken from leaf litter',
       '🪲 Orthoptera (crickets) — surface hunting at night; large crickets',
       '🪲 Diptera larvae (blow fly pupae) — found in soil and dung; not captive supplement',
       '🍄 Mesophellia species (native truffle) — KEY hypogeous fungi; sniffed then dug',
       '🍄 Hysterangium species (underground fungi) — root-associated fungi important',
       '🍄 Rhizopogon species — in eucalyptus forest, root-associated',
       '🌱 Native tubers and corms — Dichasium, Burchardia, Bulbine species',
       '🍎 Native berries (opportunistic) — Billardiera, Coprosma when available',
       '🪲 Centipedes (Scolopendra, Ethmostigmus) — occasionally; in leaf litter',
     ],
     habitat:['Heath','Wet Sclerophyll understorey','Coastal scrub','Dense gardens with deep mulch'],
     hollow:false,nocturnal:true,range:'1–5 ha',
     risks:{cats:'r',foxes:'r',dogs:'r','garden clearing':'r'},
     cap:{km:2,max:4,mo:6},
     notes:'Southern Brown Bandicoots build nests of dry vegetation on the ground — provide a nest box with plenty of dry grass, leaf litter, and bark. They are fastidious about nest conditions. Hypogeous fungi are critically important in the diet — without access to these underground fungi, bandicoots in captivity may develop nutritional deficiencies. Source: Seebeck (1990); ERS Bandicoot care sheet.',
     release:'Predator-managed (cat/fox-controlled) site mandatory. Dense understorey with deep leaf litter. Earthworm-rich soil confirmed at site. Release at dusk with food cache.'},

    {id:'eastern_barred_bandicoot',name:'Eastern Barred Bandicoot',scientific:'Perameles gunnii',color:'#292524',
     group:'Bandicoots',
     food:[
       '🪲 Earthworms — primary captive and wild food; live Lumbricus or fresh-killed',
       '🪲 Invertebrate larvae (Coleoptera curl grubs) — dug from soil; essential',
       '🪲 Orthoptera (small crickets) — calcium-dusted in captivity',
       '🪲 Isoptera (termites) — from moist clay soil and wood',
       '🪲 Amphipoda (terrestrial amphipods) — moist leaf litter and mulch',
       '🪲 Mealworms (Tenebrio molitor) — calcium-dusted, offered sparingly',
       '🍄 Hypogeous fungi (Mesophellia, Rhizopogon) — critical dietary component',
       '🍄 Endogone species (endophytic fungi) — root-associated',
       '🌱 Native tubers (Burchardia, Dichopogon) — small tubers in native grassland',
       '🌱 Grass seeds — occasionally gleaned from native grass heads',
       '🍎 Berries (Billardiera, Acrotriche) — opportunistic when available',
     ],
     habitat:['Native grassland','Grassy Woodland','Western Volcanic Plains grassland'],
     hollow:false,nocturnal:true,range:'1–5 ha',
     risks:{cats:'r',foxes:'r','grassland clearing':'r'},
     cap:{km:2,max:4,mo:6},
     endangered:'Endangered (EPBC Act)',
     notes:'🔴 ENDANGERED. Eastern Barred Bandicoot is one of Australia\'s most endangered mammals. Any rescue must be reported to DEECA Conservation Regulator immediately. They are characterised by 2–4 pale bars on the hindquarters (absent in southern brown bandicoot). There is an active captive breeding and reintroduction program — consult DSE/Zoos Victoria before any release attempt. Source: DEECA Recovery Plan (2020); Dufty (1994).',
     release:'Consult Zoos Victoria and DEECA before any release. Only release into managed predator-exclusion fenced sites. Tag and microchip required. Post-release monitoring mandatory.'},

    // ── POTOROOS (ADDITIONAL) ──────────────────────────────────────────────────
    {id:'long_nosed_potoroo',name:'Long-nosed Potoroo',scientific:'Potorous tridactylus',color:'#3f3f46',
     group:'Potoroos & Bettongs',
     food:[
       '🍄 Mesophellia species (native truffle) — PRIMARY food; hypogeous fungi critical',
       '🍄 Hysterangium species (underground fungi) — root-associated ectomycorrhizal',
       '🍄 Rhizopogon species — in eucalyptus and wet forest associations',
       '🍄 Cortinarius species (surface fungi) — seasonal; NOT to be confused with toxic lookalikes',
       '🍄 Elaphomyces species — stag truffle; occasionally taken',
       '🪲 Invertebrates — earthworms, beetle larvae, centipedes; supplement to fungi',
       '🌱 Grass seeds and fine grasses — Microlaena, Poa spp. supplemental',
       '🌱 Native tubers (Bulbine, Dichopogon) — dig with strong forelimbs',
       '🍎 Native berries — Billardiera scandens, Rubus; seasonal supplement',
       '🌿 Young plant material — shoots and green growth; secondary dietary role',
       '🪲 Mealworms (Tenebrio molitor) — calcium-dusted; captive protein supplement',
       '🪲 Crickets — gut-loaded; small to medium specimens',
     ],
     habitat:['Wet Sclerophyll Forest','Dense heath with Banksia and Leptospermum','Coastal heathland'],
     hollow:false,nocturnal:true,range:'5–20 ha',
     risks:{cats:'r',foxes:'r','habitat loss':'r'},
     cap:{km:3,max:4,mo:12},
     notes:'Long-nosed Potoroos are keystone ecosystem engineers — their digging and fungi-eating disperses fungal spores essential for tree growth. Hypogeous fungi are CRITICAL in captivity; without them, nutritional decline occurs rapidly. You can source native truffles (Mesophellia, Rhizopogon) from forest soil in moist eucalyptus woodland. Source: Johnson (1994) potoroo mycology; general potoroo husbandry.',
     release:'Dense heath or wet sclerophyll with diverse fungi assemblage confirmed. Cat-free or predator-managed preferred. Night release at food-rich site.'},

    {id:'long_footed_potoroo',name:'Long-footed Potoroo',scientific:'Potorous longipes',color:'#52525b',
     group:'Potoroos & Bettongs',
     food:[
       '🍄 Mesophellia species (native truffle) — hypogeous fungi; genus shared with sympatric P. tridactylus diet',
       '🍄 Rhizopogon species (underground fungi) — eucalypt/wet-forest root associations',
       '🍄 Hysterangium species (underground fungi) — root-associated ectomycorrhizal',
       '🍄 Cortinarius species (surface/near-surface fungi) — seasonal; avoid toxic lookalikes',
       '🍄 Elaphomyces species (stag truffle) — occasionally taken',
       '🪲 Soil-dwelling invertebrates — beetle larvae, earthworms; confirmed secondary diet component',
       '🌱 Native seeds — confirmed minor dietary component in published diet studies',
       '🌱 Plant material / green shoots — confirmed minor dietary component',
       '🍎 Native fruits — occasional, opportunistic',
       '🪲 Mealworms (Tenebrio molitor) — calcium-dusted; captive protein supplement',
       '🪲 Crickets — gut-loaded; small specimens',
     ],
     habitat:['Cool Temperate Rainforest margins','Wet Sclerophyll Forest','Damp gully forest (East Gippsland / Central Highlands)'],
     hollow:false,nocturnal:true,range:'20–75 ha (larger home range than P. tridactylus)',
     risks:{cats:'r',foxes:'r','habitat loss':'r','logging/disturbance':'r'},
     cap:{km:3,max:4,mo:12},
     notes:'State-listed threatened species with a highly restricted Victorian range (East Gippsland, Central Highlands, far-eastern NSW border ranges). An obligate fungivore — published research (Green 1999, Aust. J. Ecology) confirms >30 species of underground fungi in the diet, comprising the large majority of food intake, with insects, seeds and plant material as minor supplements. Species-level fungal identification specific to P. longipes is limited in the available literature; the genus-level list above reflects genera confirmed for the closely related, sympatric P. tridactylus in overlapping wet-forest habitat — flagged here as genus-level confidence, not a fabricated species-specific list. DO NOT release without confirming this is genuinely P. longipes and not P. tridactylus — the two are easily confused in the field; misidentification risks releasing a threatened species into the wrong management area.',
     release:'Only ever release into confirmed, current P. longipes range (East Gippsland / Central Highlands) with DEECA/relevant recovery-team consultation given threatened status. Wet forest or rainforest-margin habitat with confirmed diverse hypogeous fungi assemblage required.'},

    // ── BATS ────────────────────────────────────────────────────────────────────
    {id:'grey_headed_flying_fox',name:'Grey-headed Flying-fox',scientific:'Pteropus poliocephalus',color:'#4c1d95',
     group:'Bats',
     food:[
       '🌸 Eucalyptus camaldulensis (River Red Gum) — blossom/nectar; primary Victorian food source',
       '🌸 Eucalyptus tereticornis (Forest Red Gum) — blossom/nectar',
       '🌸 Eucalyptus melliodora (Yellow Box) — blossom/nectar',
       '🌸 Eucalyptus botryoides (Bangalay) — blossom/nectar; Gippsland coastal',
       '🌸 Eucalyptus globoidea (White Stringybark) — blossom/nectar; East Gippsland',
       '🌸 Corymbia maculata (Spotted Gum) — blossom/nectar; East Gippsland native, also widely planted',
       '🌸 Banksia integrifolia (Coast Banksia) — nectar; confirmed native diet species',
       '🍎 Ficus macrophylla (Moreton Bay Fig) — fruit; common in Melbourne parks/streets',
       '🍎 Ficus obliqua (Small-leaved Fig) — fruit',
       '🍎 Syzygium smithii (Lilly Pilly) — fruit',
       '🍃 Populus species (poplar) — leaves; supplementary browse, confirmed urban diet component',
     ],
     habitat:['Urban Parkland / Street Trees','Riparian / Waterway Corridor','Remnant coastal forest and woodland'],
     hollow:false,nocturnal:true,range:'Forages 5–15km from camp nightly, up to 50km recorded',
     risks:{'heat stress':'r','powerlines':'r','netting/barbed wire':'r','habitat loss':'o'},
     cap:{km:10,max:6,mo:12},
     notes:'Nationally listed vulnerable species. Diet confirmed via direct feeding observation and faecal/spat material analysis (native diet-species list, Sydney/Ku-ring-gai Bat Conservation Society). Melbourne studies (SWIFFT) record ~13 tree species indigenous to Melbourne plus ~87 planted street species and ~45 backyard species used by flying-foxes, with roughly 90% of planted street-tree species in a given area utilised. Extreme heat events (>40°C) cause mass mortality and are a major Victorian rescue trigger for this species — check Wildlife Victoria heat-stress protocols before intervening on a large scale.',
     release:'Only ever release to a registered flying-fox carer/rehabilitator — never a solo release. Colony species; requires soft-release into an active camp under experienced flying-fox rehabilitation guidance.'},

    {id:'microbat',name:'Microbat (various Victorian species)',scientific:'Multiple — see notes',color:'#312e81',
     group:'Bats',
     food:[
       '🪲 Diptera (moths and flies) — primary prey of most insectivorous microbats',
       '🪲 Lepidoptera (moths, especially Noctuid moths) — night-flying moths; major food source',
       '🪲 Coleoptera (beetles) — taken in flight, especially cockchafers (Anoplognathus)',
       '🪲 Trichoptera (caddisflies) — taken over water by Myotis, Vespadelus near streams',
       '🪲 Ephemeroptera (mayflies) — taken over streams; important for water bats',
       '🪲 Hymenoptera (small wasps and ants, winged forms) — taken in swarms',
       '🪲 Blowflies (Calliphora vomitoria) — captive use: cultured for feeding',
       '🪲 Mealworms (Tenebrio molitor) — captive ONLY; calcium-dusted, essential',
       '🪲 Crickets (Acheta domesticus) — small juveniles only; captive supplement',
       '🪲 Waxworms (Galleria mellonella) — high fat; limited supplement in captivity',
       '🪲 Cockroaches (small species, Blabberus) — captive feeding only',
     ],
     habitat:['Hollow-bearing trees','Building roofs and wall cavities','Caves','Rock crevices'],
     hollow:true,nocturnal:true,range:'Highly variable by species',
     risks:{cats:'r',powerlines:'o','barbed wire':'o'},
     cap:{km:1,max:20,mo:3},
     notes:'⚠️ ABLV WARNING: ALL bats in Australia should be assumed to carry Australian Bat Lyssavirus (ABLV) until proven otherwise. Only vaccinated and trained handlers should handle ANY bat. If you are bitten or scratched by a bat, seek medical advice immediately — post-exposure prophylaxis must begin within 24 hours. Common Victorian microbats include: Gould\'s Wattled Bat (Chalinolobus gouldii), Little Forest Bat (Vespadelus vulturnus), South-eastern Long-eared Bat (Nyctophilus corbeni), Chocolate Wattled Bat (Chalinolobus morio). Source: NSW Health ABLV guidelines; Bat Care Inc. protocols.',
     release:'Release at dusk from point of rescue or known roost site. Microbats navigate by echolocation — releasing during clear conditions, not rain or cold fronts. Ensure fully flight-capable before release. Match release site to species ecology (waterway vs forest vs urban).'},
  ];
  const SPM={}; SPECIES.forEach(s=>SPM[s.id]=s);

  // ═══════════════════════════════════════════════════
  // DEMO DATA — 6 realistic Victorian animals for testing
  // ═══════════════════════════════════════════════════
  const DEMO_ANIMALS={
    'demo_001':{id:'demo_001',species:'brushtail',animalRef:'BTP-24-001',status:'released',browseStage:'prerelease',
      shared:{species:'brushtail',cause:'vehicle',date:'2024-08-15',gridLat:-37.82,gridLng:145.24,location:'Bayswater VIC'},
      intake:{date:'2024-08-15',lat:-37.8236,lng:145.2450,location:'Mountain Hwy, Bayswater VIC',cause:'vehicle'},
      release:{date:'2024-11-20',lat:-37.7891,lng:145.2834,location:'Dandenong Ranges NP, Ferntree Gully',habitat:'wet_schlerophyll',carer:'Habi-Food Demo Shelter',privacy:'anonymous'},
      releaseShared:{species:'brushtail',date:'2024-11-20',gridLat:-37.79,gridLng:145.28,habitat:'wet_schlerophyll',location:'Dandenong Ranges NP'},
      sightings:{s001:{date:'2024-12-03',lat:-37.7902,lng:145.2821,condition:'healthy',by:'Ranger',notes:'Foraging in manna gums 200m from release. Joey visible in pouch.'},
                 s002:{date:'2025-01-14',lat:-37.7888,lng:145.2855,condition:'healthy',by:'Volunteer',notes:'Joey now travelling independently alongside mother.'}},
      private:{carer:'Habi-Food Demo Shelter',region:'Yarra Ranges'},created:'2024-08-15T08:30:00Z'},

    'demo_002':{id:'demo_002',species:'koala',animalRef:'KOA-24-002',status:'in_care',browseStage:'browseplus',
      browseNote:'Accepting E. viminalis well. Chlamydia treatment day 14 — vet review Thursday.',
      shared:{species:'koala',cause:'dog',date:'2024-10-03',gridLat:-37.67,gridLng:144.88,location:'Whittlesea VIC'},
      intake:{date:'2024-10-03',lat:-37.6745,lng:144.8823,location:'Plenty Rd, Whittlesea VIC',cause:'dog'},
      sightings:{},private:{carer:'Habi-Food Demo Shelter',region:'Whittlesea'},created:'2024-10-03T14:20:00Z'},

    'demo_003':{id:'demo_003',species:'ringtail',animalRef:'RTP-24-003',status:'released',browseStage:'prerelease',
      shared:{species:'ringtail',cause:'cat',date:'2024-09-08',gridLat:-37.86,gridLng:145.07,location:'Camberwell VIC'},
      intake:{date:'2024-09-08',lat:-37.8566,lng:145.0731,location:'Camberwell Rd, Camberwell VIC',cause:'cat'},
      release:{date:'2024-11-30',lat:-37.8490,lng:145.0612,location:'Hartwell Lake Reserve, Camberwell',habitat:'urban_parkland',carer:'Habi-Food Demo Shelter',privacy:'anonymous'},
      releaseShared:{species:'ringtail',date:'2024-11-30',gridLat:-37.85,gridLng:145.06,habitat:'urban_parkland',location:'Hartwell Lake Reserve'},
      sightings:{s001:{date:'2024-12-20',lat:-37.8492,lng:145.0620,condition:'healthy',by:'Reserve ranger',notes:'Drey in tea-tree 4m height. Observed foraging at night.'}},
      private:{carer:'Habi-Food Demo Shelter',region:'Boroondara'},created:'2024-09-08T19:45:00Z'},

    'demo_004':{id:'demo_004',species:'wombat',animalRef:'WOM-24-004',status:'missing',browseStage:'prerelease',
      shared:{species:'wombat',cause:'vehicle',date:'2024-07-22',gridLat:-37.75,gridLng:145.62,location:'Warburton VIC'},
      intake:{date:'2024-07-22',lat:-37.7512,lng:145.6234,location:'Warburton Hwy, Warburton VIC',cause:'vehicle'},
      release:{date:'2024-11-28',lat:-37.7380,lng:145.6188,location:'Warburton State Forest',habitat:'dry_schlerophyll',carer:'Habi-Food Demo Shelter',privacy:'named',releaser:'Demo Shelter'},
      releaseShared:{species:'wombat',date:'2024-11-28',gridLat:-37.74,gridLng:145.62,habitat:'dry_schlerophyll',location:'Warburton State Forest'},
      alert:{active:true,message:'Not sighted 6 weeks post-release. Green cable tie right ear. Last burrow near Donna Buang Rd.',contact:'Demo Shelter — 0412 XXX XXX',lat:-37.7380,lng:145.6188,posted_by:'Demo Shelter',posted_at:'2025-01-15T09:00:00Z'},
      sightings:{},private:{carer:'Habi-Food Demo Shelter',region:'Yarra Ranges'},created:'2024-07-22T07:15:00Z'},

    'demo_005':{id:'demo_005',species:'kangaroo',animalRef:'EGL-24-005',status:'in_care',browseStage:'transition',
      browseNote:'Starting on kangaroo grass — small handful alongside formula. Eating independently now.',
      shared:{species:'kangaroo',cause:'orphaned',date:'2024-12-01',gridLat:-37.90,gridLng:145.18,location:'Hallam VIC'},
      intake:{date:'2024-12-01',lat:-37.9012,lng:145.1823,location:'Hallam Valley Trail, Hallam VIC',cause:'orphaned'},
      sightings:{},private:{carer:'Habi-Food Demo Shelter',region:'Casey'},created:'2024-12-01T10:00:00Z'},

    'demo_006':{id:'demo_006',species:'sugar_glider',animalRef:'SGL-24-006',status:'released',browseStage:'prerelease',
      shared:{species:'sugar_glider',cause:'entangle',date:'2024-08-30',gridLat:-37.92,gridLng:145.34,location:'Belgrave VIC'},
      intake:{date:'2024-08-30',lat:-37.9234,lng:145.3421,location:'Sherbrooke Forest, Belgrave VIC',cause:'entangle'},
      release:{date:'2024-10-15',lat:-37.9198,lng:145.3388,location:'Sherbrooke Forest, Belgrave',habitat:'wet_schlerophyll',carer:'Habi-Food Demo Shelter',privacy:'named',releaser:'Demo Shelter'},
      releaseShared:{species:'sugar_glider',date:'2024-10-15',gridLat:-37.92,gridLng:145.34,habitat:'wet_schlerophyll',location:'Sherbrooke Forest'},
      sightings:{s001:{date:'2024-11-08',lat:-37.9196,lng:145.3390,condition:'healthy',by:'Forest volunteer',notes:'Group of 4-5 gliders observed in Acacia at dusk.'}},
      private:{carer:'Habi-Food Demo Shelter',region:'Knox'},created:'2024-08-30T20:00:00Z'},
  };
  // ═══════════════════════════════════════════════════
  // DEMO OPERATIONAL EVENTS — what this looks like when data is connected
  // ═══════════════════════════════════════════════════
  // ── OPS EVENTS: dates are always relative to today ──
  // daysOut is computed live in getFilteredEvents() — never hardcoded
  function makeDate(daysFromNow){
    const d=new Date();d.setDate(d.getDate()+daysFromNow);
    return d.toISOString().split('T')[0];
  }
  function makeEndDate(daysFromNow,durationDays){
    const d=new Date();d.setDate(d.getDate()+daysFromNow+durationDays);
    return d.toISOString().split('T')[0];
  }

  const DEMO_OPS_EVENTS=[
    {type:'burn',get date(){return makeDate(9)},get endDate(){return makeEndDate(9,3)},
     title:'FFMVic Planned Burn — Hampton Park / Lyndhurst',
     location:'Hampton Park — EVC 56 Swampy Riparian Woodland, Casey LGA',
     area_ha:67,evc:'EVC 56 Swampy Riparian Woodland',
     species:['Common brushtail possum (primary)','Common ringtail possum','Microbat spp. (ABLV risk)','Short-beaked echidna'],
     prep:['Browse spot B2 in this area — collect before ignition date','Stock: Eucalyptus viminalis browse, Leptospermum laevigatum','Pre-contact Casey carers network','Expected rescue surge window: 0–14 days post-ignition','Suspend releases within 2km of burn perimeter for 10 weeks post-burn'],
     impact:'high'},
    {type:'arbo',get date(){return makeDate(14)},
     title:'Council arborist work order — hollow-bearing trees',
     location:'Boronia Rd, Knox — 3 Eucalyptus macrorhyncha (DBH >80cm) scheduled',
     species:['Common brushtail possum (almost certain)','Sugar glider (possible)','Owlet nightjar (nesting cavity)'],
     prep:['Pre-stage 3× possum boxes on site 1 week before felling','Pre-notify Knox carers to attend during removal','Bring pouch young kit','Contact Boronia Vet Clinic for crush injuries'],
     impact:'medium'},
    {type:'clear',get date(){return makeDate(21)},get endDate(){return makeEndDate(21,7)},
     title:'Approved native vegetation clearing — Clyde North estate',
     location:'Clyde North — 1.8ha remnant EVC 83 Plains Grassy Woodland, Casey',
     area_ha:1.8,evc:'EVC 83 Plains Grassy Woodland',
     species:['Common brushtail possum','Long-nosed bandicoot (ground-dwelling, injury risk)','Eastern grey kangaroo (likely to flee)','Eastern blue-tongue lizard'],
     prep:['Final collection window — collect from this site BEFORE clearing begins','Co-ordinate 3+ carers for clearing day','Stock: eucalyptus browse, native grasses, insectivore supplement','Alert Cranbourne Vet for intake surge'],
     impact:'high'},
    {type:'maint',get date(){return makeDate(5)},
     title:'Council roadside slashing',
     location:'Thompsons Rd corridor — 4.8km, Casey / Cardinia boundary',
     species:['Common ringtail possum (disturbed from understorey)','Short-beaked echidna (ground disturbance)','Long-nosed bandicoot'],
     prep:['Food collection window: collect from this corridor BEFORE slashing date','Post-slash: anticipate 3–5 days of displaced animal calls from this strip'],
     impact:'low'},
    {type:'burn',get date(){return makeDate(28)},get endDate(){return makeEndDate(28,3)},
     title:'FFMVic Planned Burn — Dandenong Ranges NP',
     location:'Menzies Creek / Belgrave area — Wet Sclerophyll Forest, Yarra Ranges',
     area_ha:180,evc:'EVC 30 Wet Sclerophyll Forest (Shrubby)',
     species:['Common brushtail possum','Common ringtail possum','Sugar glider (check hollow trees on fire perimeter)','Southern brown bandicoot','Superb lyrebird (disturbed)'],
     prep:['Stock: Eucalyptus viminalis browse, Leptospermum, apple and native fruits','Pre-contact Dandenong Ranges carers','Alert Healesville Sanctuary to possible intake surge','Release site suspension: Sherbrooke Forest — hold for 8 weeks post-burn'],
     impact:'high'},
    {type:'chem',get date(){return makeDate(-2)},
     title:'Council herbicide spray — roadside (active)',
     location:'Stud Rd corridor — Knox / Maroondah boundary (6.2km)',
     species:['Browse collection UNSAFE — re-entry interval 21 days',`Safe from: ${makeDate(19)}`],
     prep:['DO NOT collect from Stud Rd corridor roadside vegetation until safe date','Chemical: metsulfuron-methyl (re-entry 21 days)','Update volunteer sheet DO NOT COLLECT banner — active'],
     impact:'high'},
    {type:'plant',get date(){return makeDate(35)},
     title:'Revegetation planting — Dandenong Creek corridor',
     location:'Ringwood — 1.2km riparian corridor, Melbourne Water managed land',
     species_note:'220× Eucalyptus viminalis, 180× Acacia melanoxylon, 140× Melaleuca ericifolia',
     future:'Food source from ~2028 (shrub layer) / ~2030 (canopy)',
     prep:['Record as future browse and release corridor — Ferntree Gully / Ringwood zone','Add to 5-year release planning: brushtail possum, ringtail possum, sugar glider','Revisit planting site survey: October 2028'],
     impact:'positive'},
    {type:'burn',get date(){return makeDate(45)},get endDate(){return makeEndDate(45,4)},
     title:'FFMVic Planned Burn — Cardinia Creek Parklands',
     location:'Beaconsfield Upper — EVC 175 Heathland, Cardinia Shire',
     area_ha:120,evc:'EVC 175 Heathy Woodland',
     species:['Swamp wallaby','Eastern grey kangaroo','Short-beaked echidna','Long-nosed potoroo (if present)'],
     prep:['Browse: kangaroo grass, wallaby grass, lomandra required post-rescue','Alert Cardinia shire carers — Beaconsfield / Emerald zone','iNaturalist monitoring: flag this area for 4, 8, 12 week recovery checks'],
     impact:'medium'},
  ];


  // ═══════════════════════════════════════════════════
  // BROWSE STAGES
  // Each animal has a stage that drives what browse is needed.
  // Carer taps to advance stage — takes 2 seconds, updates everything.
  // ═══════════════════════════════════════════════════
  const BROWSE_STAGES={
    formula:{label:'Formula only',sub:'No browse yet',icon:'🍼',
      needs:{},
      note:'Collect nothing for this animal yet. Focus on next stage preparation.'},
    transition:{label:'Transitioning',sub:'Formula + first browse',icon:'🌱',
      needs:{brushtail:['Eucalyptus viminalis (manna gum) — 2-3 small leaves only'],ringtail:['Leptospermum laevigatum — 1-2 small sprigs'],koala:['Eucalyptus viminalis — 3-4 leaves, no stems'],sugar_glider:['Banksia spinulosa — nectar from 1 flower head'],wombat:['Rytidosperma species — small handful fresh grass'],kangaroo:['Themeda triandra — small handful fresh grass'],echidna:['Earthworm supplement — no browse'],bandicoot:['Earthworm supplement — no browse'],feathertail:['Banksia spinulosa — nectar only'],swamp_wallaby:['Themeda triandra — small handful'],platypus:"[\"Ephemeroptera (mayfly larvae) — small quantities, monitor acceptance\",\"Plecoptera (stonefly larvae) — small quantities, monitor acceptance\"]",tiger_quoll:"[\"Insects and large invertebrates — small quantities, monitor acceptance\",\"Crayfish and freshwater yabbies — small quantities, monitor acceptance\"]",antechinus:"[\"Coleoptera (beetles and larvae) — small quantities, monitor acceptance\",\"Orthoptera (crickets and grasshoppers) — small quantities, monitor acceptance\"]",dunnart:"[\"Acari (mites and small arachnids) — small quantities, monitor acceptance\",\"Isopoda (slaters, Armadillidium) — small quantities, monitor acceptance\"]",mountain_brushtail:"[\"Eucalyptus obliqua (messmate stringybark) — small amounts, introduce gradually\",\"Eucalyptus regnans (mountain ash) — small amounts, introduce gradually\"]",greater_glider:"[\"Eucalyptus obliqua (messmate) — small amounts, introduce gradually\",\"Eucalyptus regnans (mountain ash) — small amounts, introduce gradually\"]",leadbeaters_possum:"[\"Acacia gum and exudate — small amounts, introduce gradually\",\"Eucalyptus sap — small amounts, introduce gradually\"]",western_grey_kangaroo:"[\"Themeda triandra (kangaroo grass) — small amounts, introduce gradually\",\"Austrodanthonia species (wallaby grass) — small amounts, introduce gradually\"]",red_necked_wallaby:"[\"Themeda triandra (kangaroo grass) — small amounts, introduce gradually\",\"Poa labillardieri (tussock poa) — small amounts, introduce gradually\"]",southern_brown_bandicoot:"[\"Earthworms (Lumbricus terrestris) — small quantities, monitor acceptance\",\"Coleoptera larvae (curl grubs, scarab grubs) — small quantities, monitor acceptance\"]",eastern_barred_bandicoot:"[\"Earthworms — small quantities, monitor acceptance\",\"Invertebrate larvae (Coleoptera curl grubs) — small quantities, monitor acceptance\"]",long_nosed_potoroo:"[\"Mesophellia species (native truffle) — small quantities, monitor acceptance\",\"Hysterangium species (underground fungi) — small quantities, monitor acceptance\"]",microbat:"[\"Diptera (moths and flies) — small quantities, monitor acceptance\",\"Lepidoptera (moths, especially Noctuid moths) — small quantities, monitor acceptance\"]"},
      note:'Tiny amounts alongside formula. Watch for acceptance before increasing.'},
    browseplus:{label:'Browse primary',sub:'Browse + formula top-up',icon:'🌿',
      needs:{brushtail:['Eucalyptus viminalis — 6-8 branchlets 30cm','Eucalyptus radiata — 3-4 branchlets','Acacia mearnsii — 2 branchlets'],ringtail:['Leptospermum laevigatum — 5-6 branchlets','Eucalyptus viminalis — 3-4 branchlets','Rosa species — 2 sprigs if available'],koala:['Eucalyptus viminalis — 8-10 branchlets (primary)','Eucalyptus radiata — 4-5 branchlets'],sugar_glider:['Banksia spinulosa — 2-3 flower heads','Eucalyptus species — 3-4 branchlets for sap/nectar','Acacia melanoxylon — 1-2 branchlets (gum source)'],wombat:['Rytidosperma species — large handful fresh','Poa species — large handful','Carex species — small handful'],kangaroo:['Themeda triandra — large bunch fresh','Poa labillardieri — medium bunch'],echidna:['Wombaroo Insectivore Mix — no browse required'],bandicoot:['Wombaroo Insectivore Mix','Earthworms — if accessible'],feathertail:['Banksia spinulosa — 3-4 heads','Grevillea species — 2-3 sprigs when flowering'],swamp_wallaby:['Themeda triandra — large bunch','Acacia browse — 2-3 branchlets'],platypus:"[\"Ephemeroptera (mayfly larvae) — primary diet, live/fresh daily\",\"Plecoptera (stonefly larvae) — primary diet, live/fresh daily\",\"Trichoptera (caddisfly larvae) — primary diet, live/fresh daily\",\"Diptera larvae (midge larvae, chironomids) — primary diet, live/fresh daily\"]",tiger_quoll:"[\"Insects and large invertebrates — primary diet, live/fresh daily\",\"Crayfish and freshwater yabbies — primary diet, live/fresh daily\",\"Fruit and berries — primary diet, live/fresh daily\",\"Small mammals — primary diet, live/fresh daily\"]",antechinus:"[\"Coleoptera (beetles and larvae) — primary diet, live/fresh daily\",\"Orthoptera (crickets and grasshoppers) — primary diet, live/fresh daily\",\"Lepidoptera larvae (caterpillars and moths) — primary diet, live/fresh daily\",\"Araneae (spiders) — primary diet, live/fresh daily\"]",dunnart:"[\"Acari (mites and small arachnids) — primary diet, live/fresh daily\",\"Isopoda (slaters, Armadillidium) — primary diet, live/fresh daily\",\"Insect larvae (various) — primary diet, live/fresh daily\",\"Collembola (springtails) — primary diet, live/fresh daily\"]",mountain_brushtail:"[\"Eucalyptus obliqua (messmate stringybark) — primary diet, fresh daily\",\"Eucalyptus regnans (mountain ash) — primary diet, fresh daily\",\"Eucalyptus delegatensis (alpine ash) — primary diet, fresh daily\",\"Acacia melanoxylon (blackwood) — primary diet, fresh daily\"]",greater_glider:"[\"Eucalyptus obliqua (messmate) — primary diet, fresh daily\",\"Eucalyptus regnans (mountain ash) — primary diet, fresh daily\",\"Eucalyptus delegatensis (alpine ash) — primary diet, fresh daily\",\"Eucalyptus cypellocarpa (mountain grey gum) — primary diet, fresh daily\"]",leadbeaters_possum:"[\"Acacia gum and exudate — primary diet, fresh daily\",\"Eucalyptus sap — primary diet, fresh daily\",\"Lerp (psyllid secretions) — primary diet, fresh daily\",\"Honeydew (Spondyliaspis, Ctenarytaina) — primary diet, fresh daily\"]",western_grey_kangaroo:"[\"Themeda triandra (kangaroo grass) — primary diet, fresh daily\",\"Austrodanthonia species (wallaby grass) — primary diet, fresh daily\",\"Dicanthium sericeum (Queensland blue grass) — primary diet, fresh daily\",\"Microlaena stipoides (weeping grass) — primary diet, fresh daily\"]",red_necked_wallaby:"[\"Themeda triandra (kangaroo grass) — primary diet, fresh daily\",\"Poa labillardieri (tussock poa) — primary diet, fresh daily\",\"Microlaena stipoides (weeping grass) — primary diet, fresh daily\",\"Rytidosperma species (wallaby grass) — primary diet, fresh daily\"]",southern_brown_bandicoot:"[\"Earthworms (Lumbricus terrestris) — primary diet, live/fresh daily\",\"Coleoptera larvae (curl grubs, scarab grubs) — primary diet, live/fresh daily\",\"Isoptera (termites) — primary diet, live/fresh daily\",\"Coleoptera adults (ground beetles, Carabidae) — primary diet, live/fresh daily\"]",eastern_barred_bandicoot:"[\"Earthworms — primary diet, live/fresh daily\",\"Invertebrate larvae (Coleoptera curl grubs) — primary diet, live/fresh daily\",\"Orthoptera (small crickets) — primary diet, live/fresh daily\",\"Isoptera (termites) — primary diet, live/fresh daily\"]",long_nosed_potoroo:"[\"Mesophellia species (native truffle) — primary diet, live/fresh daily\",\"Hysterangium species (underground fungi) — primary diet, live/fresh daily\",\"Rhizopogon species — primary diet, live/fresh daily\",\"Cortinarius species (surface fungi) — primary diet, live/fresh daily\"]",microbat:"[\"Diptera (moths and flies) — primary diet, live/fresh daily\",\"Lepidoptera (moths, especially Noctuid moths) — primary diet, live/fresh daily\",\"Coleoptera (beetles) — primary diet, live/fresh daily\",\"Trichoptera (caddisflies) — primary diet, live/fresh daily\"]"},
      note:'Primary diet now browse. Formula reducing. Monitor weight trend closely at this transition.'},
    prerelease:{label:'Pre-release browse',sub:'Wild diet only',icon:'🦘',
      needs:{brushtail:['Eucalyptus viminalis — 10+ branchlets (EVC-matched to release site)','Eucalyptus radiata — 5+ branchlets','Acacia mearnsii — 4 branchlets'],ringtail:['Leptospermum laevigatum — 8-10 branchlets','Eucalyptus viminalis — 5-6 branchlets','Rosa species — as available'],koala:['Eucalyptus viminalis — 12-15 branchlets ONLY from release site area if possible','Daily fresh — critical for pre-release acclimatisation'],sugar_glider:['Banksia spinulosa — 4-5 heads','Grevillea species — 3-4 sprigs','Acacia melanoxylon — 2 branchlets for sap'],wombat:['Fresh grass from release site area — critical for scent acclimatisation','Rytidosperma, Poa — large amounts'],kangaroo:['Grass from release site area — scent critical','Themeda triandra — large amounts daily'],echidna:['Live invertebrates only if possible — ants, termites from release site area'],bandicoot:['Live earthworms and invertebrates from release site area'],feathertail:['Flowering Banksia and Grevillea from release site — nectar critical'],swamp_wallaby:['Browse from release site EVC — Themeda, Acacia, native grasses'],platypus:"[\"Ephemeroptera (mayfly larvae) — source from release site habitat where possible\",\"Plecoptera (stonefly larvae) — source from release site habitat where possible\",\"Trichoptera (caddisfly larvae) — source from release site habitat where possible\",\"Diptera larvae (midge larvae, chironomids) — source from release site habitat where possible\",\"Amphipoda (freshwater shrimp, Gammarus, Austrochiltonia) — source from release site habitat where possible\"]",tiger_quoll:"[\"Insects and large invertebrates — source from release site habitat where possible\",\"Crayfish and freshwater yabbies — source from release site habitat where possible\",\"Fruit and berries — source from release site habitat where possible\",\"Small mammals — source from release site habitat where possible\",\"Birds and bird eggs — source from release site habitat where possible\"]",antechinus:"[\"Coleoptera (beetles and larvae) — source from release site habitat where possible\",\"Orthoptera (crickets and grasshoppers) — source from release site habitat where possible\",\"Lepidoptera larvae (caterpillars and moths) — source from release site habitat where possible\",\"Araneae (spiders) — source from release site habitat where possible\",\"Blattodea (cockroaches, Shelfordella tartara) — source from release site habitat where possible\"]",dunnart:"[\"Acari (mites and small arachnids) — source from release site habitat where possible\",\"Isopoda (slaters, Armadillidium) — source from release site habitat where possible\",\"Insect larvae (various) — source from release site habitat where possible\",\"Collembola (springtails) — source from release site habitat where possible\",\"Small crickets (Gryllodes sigillatus) — source from release site habitat where possible\"]",mountain_brushtail:"[\"Eucalyptus obliqua (messmate stringybark) — collect from release site area (scent acclimatisation)\",\"Eucalyptus regnans (mountain ash) — collect from release site area (scent acclimatisation)\",\"Eucalyptus delegatensis (alpine ash) — collect from release site area (scent acclimatisation)\",\"Acacia melanoxylon (blackwood) — collect from release site area (scent acclimatisation)\",\"Acacia dealbata (silver wattle) — collect from release site area (scent acclimatisation)\"]",greater_glider:"[\"Eucalyptus obliqua (messmate) — collect from release site area (scent acclimatisation)\",\"Eucalyptus regnans (mountain ash) — collect from release site area (scent acclimatisation)\",\"Eucalyptus delegatensis (alpine ash) — collect from release site area (scent acclimatisation)\",\"Eucalyptus cypellocarpa (mountain grey gum) — collect from release site area (scent acclimatisation)\",\"Eucalyptus radiata (narrow-leaved peppermint) — collect from release site area (scent acclimatisation)\"]",leadbeaters_possum:"[\"Acacia gum and exudate — collect from release site area (scent acclimatisation)\",\"Eucalyptus sap — collect from release site area (scent acclimatisation)\",\"Lerp (psyllid secretions) — collect from release site area (scent acclimatisation)\",\"Honeydew (Spondyliaspis, Ctenarytaina) — collect from release site area (scent acclimatisation)\",\"Manna (E. viminalis exudate) — collect from release site area (scent acclimatisation)\"]",western_grey_kangaroo:"[\"Themeda triandra (kangaroo grass) — collect from release site area (scent acclimatisation)\",\"Austrodanthonia species (wallaby grass) — collect from release site area (scent acclimatisation)\",\"Dicanthium sericeum (Queensland blue grass) — collect from release site area (scent acclimatisation)\",\"Microlaena stipoides (weeping grass) — collect from release site area (scent acclimatisation)\",\"Poa labillardieri (tussock poa) — collect from release site area (scent acclimatisation)\"]",red_necked_wallaby:"[\"Themeda triandra (kangaroo grass) — collect from release site area (scent acclimatisation)\",\"Poa labillardieri (tussock poa) — collect from release site area (scent acclimatisation)\",\"Microlaena stipoides (weeping grass) — collect from release site area (scent acclimatisation)\",\"Rytidosperma species (wallaby grass) — collect from release site area (scent acclimatisation)\",\"Lolium perenne (ryegrass) — collect from release site area (scent acclimatisation)\"]",southern_brown_bandicoot:"[\"Earthworms (Lumbricus terrestris) — source from release site habitat where possible\",\"Coleoptera larvae (curl grubs, scarab grubs) — source from release site habitat where possible\",\"Isoptera (termites) — source from release site habitat where possible\",\"Coleoptera adults (ground beetles, Carabidae) — source from release site habitat where possible\",\"Orthoptera (crickets) — source from release site habitat where possible\"]",eastern_barred_bandicoot:"[\"Earthworms — source from release site habitat where possible\",\"Invertebrate larvae (Coleoptera curl grubs) — source from release site habitat where possible\",\"Orthoptera (small crickets) — source from release site habitat where possible\",\"Isoptera (termites) — source from release site habitat where possible\",\"Amphipoda (terrestrial amphipods) — source from release site habitat where possible\"]",long_nosed_potoroo:"[\"Mesophellia species (native truffle) — source from release site habitat where possible\",\"Hysterangium species (underground fungi) — source from release site habitat where possible\",\"Rhizopogon species — source from release site habitat where possible\",\"Cortinarius species (surface fungi) — source from release site habitat where possible\",\"Elaphomyces species — source from release site habitat where possible\"]",microbat:"[\"Diptera (moths and flies) — source from release site habitat where possible\",\"Lepidoptera (moths, especially Noctuid moths) — source from release site habitat where possible\",\"Coleoptera (beetles) — source from release site habitat where possible\",\"Trichoptera (caddisflies) — source from release site habitat where possible\",\"Ephemeroptera (mayflies) — source from release site habitat where possible\"]"},
      note:'CRITICAL: Collect from or near the planned release site if possible. Scent acclimatisation improves post-release survival.'},
  };

  const STAGE_ORDER=['formula','transition','browseplus','prerelease'];

  global.HF_DOMAIN = { CAUSES, SPECIES, SPM, DEMO_ANIMALS, DEMO_OPS_EVENTS, BROWSE_STAGES, STAGE_ORDER, makeDate, makeEndDate };
})(window);
